# Generated by Django 5.1 on 2025-08-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional product image. Stored under MEDIA_ROOT/product_images/",
                null=True,
                upload_to="product_images/",
            ),
        ),
    ]
